import sqlite3

conn = sqlite3.connect('stories.db')
c = conn.cursor()

c.execute('''
CREATE TABLE IF NOT EXISTS stories (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    image TEXT
)
''')

c.execute('''
CREATE TABLE IF NOT EXISTS steps (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    story_id INTEGER NOT NULL,
    step_number INTEGER NOT NULL,
    content TEXT NOT NULL,
    option1 TEXT,
    option2 TEXT,
    next1 INTEGER,
    next2 INTEGER,
    FOREIGN KEY(story_id) REFERENCES stories(id)
)
''')

stories = [
    ('Child Rights 🧒', 'child_rights.jpg',[
        (1, 'You’re in school. A group of kids are bullying a quiet student. What will you do?', 'Join them 😬', 'Stop them ❌', 2, 3),
        (2, 'Bullying is a crime and it hurts others. This is not the right thing. You lose. 🚫',None, None, None, None),
        (3, 'Good choice! You decide to stop them. But how?', 'Fight them to save the child', 'Ask a teacher or elder for help', 4, 5),
        (4, 'Trying to fight them can make things worse. You might get hurt or punished too. Not a wise move.',None, None, None, None),
        (5, 'Perfect choice! You informed a teacher, and the bullying stopped. You helped someone safely and smartly. You win! 🏆',None, None, None, None),
    ]),
    ('Forest Adventure 🌳', 'forest_background.jpg', [
        (1, 'You wake up in a mysterious forest. Two paths lie ahead.', 'Go Left', 'Go Right', 2, 3),
        (2, 'You take the left path and find a glowing flower.', 'Pick it', 'Leave it', 4, 5),
        (3, 'You take the right path and encounter a river.', 'Swim across', 'Build a raft', 6, 7),
        (4, 'The flower grants you magical powers. You win!', None, None, None, None),
        (5, 'You leave the flower and get lost. Game over.', None, None, None, None),
        (6, 'You swim but the current is too strong. You lose!', None, None, None, None),
        (7, 'You build a raft and safely cross. You win!', None, None, None, None),
    ]),
    ('School Love 💌', 'school.jpg', [
        (1, 'You’re a shy girl in 11th standard. You’ve secretly had a crush on an intelligent boy. One day, out of nowhere, he starts talking to you because of a mutual friend.', 'Start small talks with him', 'Hide your feelings', 2, 3),
        (2, 'You start chatting a little every day. The boy slowly opens up too. But suddenly, your mutual friend shifts to another city. Now it’s just the two of you.', 'Continue talking and open up', 'Slowly drift apart', 4, 5),
        (3, 'You never made a move. You silently watch him from afar. Maybe some love stories stay in the heart only 💔', None, None, None, None),
        (4, 'In 12th standard, he becomes your study partner. He helps you in difficult topics, stays up late to explain things. You both become really close.', 'Share feelings with him', 'Stay reserved', 6, 7),
        (5, 'You both stop talking. Life moves on. Maybe love wasn’t in the cards this time.💔 Some bonds fade quietly.', None, None, None, None),
        (6, 'One day, while studying, he gently hugs you. Your heart races. You’re not sure what it means.', 'Hug him back shyly', 'Step away nervously', 8, 9),
        (7, 'You stay reserved. He assumes you’re not interested and starts maintaining distance. You both grow apart.', None, None, None, None),
        (8, 'You hug him back. Later, he looks into your eyes, whispers a soft “sorry”... and then kisses your cheek. Butterflies explode in your stomach.', 'Smile and blush', 'Get shocked and pull away', 10, 11),
        (9, 'You step away. He apologizes and respects your space. But the moment creates an awkward gap between you.', None, None, None, None),
        (10, 'Now there’s something magical between you two. He treats you more sweetly.', 'Let your feelings grow silently', 'Tell him you liked it', 12, 13),
        (11, 'You get shocked and pull away. He looks hurt. Things become a little weird between you two after that.', None, None, None, None),
        (12, 'There’s a girl in your class who’s his best friend. They laugh a lot, share jokes. You feel a sting of jealousy every time.', 'Stay silent', 'Ask him about her', 14, 15),
        (13, 'You tell him you liked it. He smiles like crazy and says, “I’m so glad.” You both start getting closer.', 'Talk about your future', 'Keep it chill', 26, 26),
        (14, 'One day while you’re all talking, someone gives the boy a chocolate. He instantly turns and gives it to his best friend. You feel crushed.', 'Stay silent', 'Walk away', 16, 17),
        (15, 'You ask him about his best friend. He says, “She’s just a friend, nothing more.” But it still hurts watching them be so close.', 'Try to trust him', 'Stay distant', 18, 19),
        (16, 'The boy notices your sadness. Next day, he brings *two chocolates* and gives them to you with a shy smile. “For yesterday,” he says. Your heart melts.', 'Blush and say thank you', 'Tease him for noticing', 20, 21),
        (17, 'You walk away. He’s confused. You both stop talking for a while. Eventually, things become distant.', None, None, None, None),
        (18, 'You try to trust him. Slowly, your bond grows deeper. He shares his dreams, his fears. You start falling in love with him for real.', 'Tell him how you feel', 'Wait for him to confess', 22, 23),
        (19, 'You stay distant. He senses it. The bond weakens. He doesn’t understand why you changed.', None, None, None, None),
        (20, 'You both start studying together even more. You steal glances while he explains things. He sometimes catches you and smiles.', 'Blush and look away', 'Hold eye contact', 24, 25),
        (21, 'He laughs when you tease him. “You notice *everything* about me?” he asks. The bond deepens.', 'Talk about your future', 'Keep it chill', 26, 27),
        (22, 'You tell him your feelings. He holds your hand and says, “I’ve been waiting to hear this.” You both become a couple. 💖', 'Talk about your future', 'Keep it chill', 26, 27),
        (23, 'You wait, and one day, he confesses. You both smile like fools and start dating.', 'Talk about your future', 'Keep it chill', 26, 27),
        (24, 'Blushing, you look away. He laughs softly. “You’re cute when you do that,” he says.', 'Say “You too”', 'Stay quiet but smile', 28, 29),
        (25, 'You hold eye contact, and the moment is magical. He tucks a hair strand behind your ear and smiles.', 'Tease him', 'Look away shyly', 30, 31),
        (26, 'You both get into different colleges in different cities. And… you’re from different castes. Will your families accept?', 'Yes, they agree 💫', 'No, they say no 🚫', 32, 33),
        (27, 'You both enjoy the relationship, but avoid serious conversations. With time, distance starts growing between you. You are not as close as you used to be.', None, None, None, None),
        (28, 'He smiles. That simple gesture feels more romantic than anything else. You feel safe with him.', 'Talk about your future', 'Keep it chill', 26, 27),
        (29, 'You smile quietly. He senses your feelings even in your silence. That’s how close you’ve become.', 'Talk about your future', 'Keep it chill', 26, 27),
        (30, 'You tease him. He laughs, blushes and calls you a “troublemaker”. You both giggle like kids.', 'Talk about your future', 'Keep it chill', 26, 27),
        (31, 'You look away, hiding your red cheeks. He doesn’t say anything—just keeps looking at you lovingly.', 'Talk about your future', 'Keep it chill', 26, 27),
        (32, 'Your families accept your love, and one day, you get married surrounded by people who supported your journey 💍💖', None, None, None, None),
        (33, 'You both promise not to give up. You want to try and make your parents understand.', 'Talk respectfully to parents', 'Run away and get married', 34, 35),
        (34, 'Through time, patience, and love—you melt your families’ hearts. They accept your relationship and bless you both.🌸 True love wins.', None, None, None, None),
        (35, 'Running away creates bigger issues. You feel guilt and sadness. Maybe you should’ve tried to talk first.🥀 Sometimes the harder road is the right one.', None, None, None, None),
    ]),
    ('Mystery Key 🔐', 'key_background.jpg', [
        (1, 'You find a locked chest. Search for key or leave it?', 'Search', 'Leave', 2, 3),
        (2, 'You find the key under a rock. Use it or keep it?', 'Use it', 'Keep it', 4, 5),
        (3, 'You leave and the secret stays forever. Game over.', None, None, None, None),
        (4, 'The chest opens with treasure! You win!', None, None, None, None),
        (5, 'You keep the key but never open chest. You lose!', None, None, None, None),
    ]),
    ('A Journey Together 🌍', 'journey_background.jpg', [
        (1, 'Sophie and Liam meet for the first time on a backpacking trip across Europe.', 'Talk more', 'Keep walking', 2, 3),
        (2, 'As they explore new cities together, they begin to share more personal stories.', 'Admit feelings', 'Stay friends', 4, 5),
        (3, 'Sophie decides to keep walking without talking, unsure of her feelings.', None, None, None, None),
        (4, 'Sophie admits her feelings, and Liam confesses his feelings in return.', None, None, None, None),
        (5, 'They decide to remain friends, parting ways after the trip.', None, None, None, None),
    ]),
    ('Haunted Mansion 🦇', 'mansion_background.jpg', [
        (1, 'You stand before a haunted mansion. Enter or walk away?', 'Enter', 'Walk Away', 2, 3),
        (2, 'A ghost appears! Do you talk or flee?', 'Talk', 'Flee', 4, 5),
        (3, 'You walk away but hear whispers behind you. Game over.', None, None, None, None),
        (4, 'The ghost reveals a hidden treasure. You win!', None, None, None, None),
        (5, 'You flee and get lost in the night. You lose!', None, None, None, None),
    ]),
    ('A Second Chance ❤️', 'second_chance_background.jpg', [
        (1, 'Vivian and Zyan run into each other years after their breakup in a coffee shop.', 'Talk to Zyan', 'Walk away', 2, 3),
        (2, 'They have an awkward conversation but the chemistry is undeniable. Old feelings resurface.', 'Give him a second chance', 'Leave the conversation', 4, 5),
        (3, 'Vivian decides to walk away, leaving behind unresolved emotions and a sense of regret.', None, None, None, None),
        (4, 'Vivian gives Zyan a second chance, and they reconnect, starting fresh.', None, None, None, None),
        (5, 'Vivian decides not to reopen old wounds and moves on with her life.', None, None, None, None),
    ]),
    ('Enchanted Garden 🌸', 'magical_background.jpg', [
        (1, 'Alice discovers a hidden entrance to a magical garden behind her grandmother’s house.', 'Enter the garden', 'Leave the garden', 2, 3),
        (2, 'Inside the garden, she finds a magical fountain. She can drink from it or leave.', 'Drink from the fountain', 'Leave the fountain', 4, 5),
        (3, 'Alice leaves and never knows the garden’s secrets. Game over.', None, None, None, None),
        (4, 'Drinking from the fountain gives Alice magical powers. She wins the game!', None, None, None, None),
        (5, 'Leaving the fountain causes the gate to disappear forever. Alice loses the chance to return.', None, None, None, None),
    ]),
    ('A New Beginning 💑', 'new_beginnings_background.jpg', [
        (1, 'Anna and Jack meet at a mutual friend’s dinner party. They hit it off immediately.', 'Talk more to Jack', 'Move away', 2, 3),
        (2, 'They spend the evening talking and laughing. Anna feels a spark.', 'Ask for his number', 'Enjoy the night', 4, 5),
        (3, 'Anna decides to move away from Jack, unsure if she wants a relationship.', None, None, None, None),
        (4, 'Anna asks for Jack’s number, and they plan to meet again. A new chapter begins.', None, None, None, None),
        (5, 'Anna enjoys the night, but they part ways, leaving things unresolved.', None, None, None, None),
    ]),
    ('The Start of Us 💖', 'first_kiss_background.jpg', [
        (1, 'Emma and James reconnect at a friend\'s wedding. They share fond memories of their childhood.', 'Hug Emma', 'Pull away', 2, 3),
        (2, 'They spend the evening together, talking and laughing. The chemistry between them grows stronger.', 'Kiss James', 'Move away', 4, 5),
        (3, 'Emma pulls away unsure of her feelings. They both stand in awkward silence.', 'Give it a chance', 'Leave the scene', 6, 7),
        (4, 'James steals a sweet kiss under the stars, and Emma is filled with joy and butterflies.', None, None, None, None),
        (5, 'Emma decides to leave the event early, feeling conflicted about her feelings for James.', None, None, None, None),
        (6, 'Emma decides to give it a chance and feels their connection deepening.', None, None, None, None),
        (7, 'She leaves, feeling uncertain about the future of their relationship.', None, None, None, None),
    ]),
    ('Transfer Student 🔪', 'transfer_student.jpg',[
        (1, 'You notice something strange the moment the new guy walks into class. He’s polite, perfect, and smiling—but your stomach knots.', 'Smile back and ignore your gut', 'Secretly search his name online', 2, 3),
        (2, 'You try to blend in, but can’t shake the feeling. He starts sitting next to you. He remembers everything you say.', 'Be polite', 'Tell him to back off', 4, 5),
        (3, 'You search his name. Nothing comes up—until you reverse image search his face. A missing boy from 3 years ago... same eyes.', 'Tell your best friend', 'Confront him', 6, 7),
        (4, 'He offers to walk you home. It’s getting dark. You agree. He hums an old song—you’ve heard it before… in a crime doc.', 'Ask about the song', 'Change the topic', 8, 9),
        (5, 'You push him away. The next morning, your bike tires are slashed and your locker has a note: “Don’t try that again.”', 'Show it to the principal', 'Burn the note', 10, 11),
        (6, 'Your best friend laughs it off—until she goes missing that night. Her last text: "You were right."', 'Go to the police', 'Search her house', 12, 13),
        (7, 'You casually mention what you found. His expression freezes. “You shouldn’t have done that,” he whispers, smiling.', 'Run', 'Play dumb', 14, 15),
        (8, 'He pauses. “My brother used to sing that.” His voice cracks. He never mentioned a brother before.', 'Ask more', 'Stay quiet', 16, 17),
        (9, 'He smiles. Too perfectly. Later, you find a photo slipped into your locker: your childhood house circled in red.', 'Show your parents', 'Hide it', 18, 19),
        (10, 'The principal laughs it off as a prank. But the new guy watches you the whole day, eyes never blinking.', None, None, None, None),
        (11, 'You burn it. That night, you get a text from a hidden number: "Nice try, firestarter."', None, None, None, None),
        (12, 'The police take your statement. Days pass. Nothing happens. Until you wake up with her bracelet on your pillow.', None, None, None, None),
        (13, 'Her room is neat. Too neat. Inside her closet is a hidden note: "Don’t trust anyone. Especially him."', None, None, None, None),
        (14, 'You run. He doesn’t follow. But that night, your window is open—and you’re sure you locked it.', None, None, None, None),
        (15, 'You laugh. "Just kidding." He leans closer: "Good. Because I’d hate to hurt you."', None, None, None, None),
        (16, 'He opens up. "He died. Everyone thinks I did it." You realize he’s the boy from the case… but he’s protecting someone else.', None, None, None, None),
        (17, 'You stay silent. That night, he sends you a photo: him at your front door. "Goodnight, detective."', None, None, None, None),
        (18, 'Your parents panic. They report it. That night, police surround your home—but he’s already inside.', None, None, None, None),
        (19, 'You hide it. But it’s too late. The photo was taken yesterday. He’s been watching you sleep.', None, None, None, None)
    ]),
    ('Lost Island 🏝️', 'island_backgorund.jpg', [
        (1, 'Your ship docks at a mysterious island. Explore or sail away?', 'Explore', 'Sail Away', 2, 3),
        (2, 'You find an ancient temple. Enter or camp outside?', 'Enter', 'Camp', 4, 5),
        (3, 'You sail away safely but miss an adventure. Game over.', None, None, None, None),
        (4, 'Inside, you discover a treasure trove. You win!', None, None, None, None),
        (5, 'You camp but get attacked by wildlife. You lose!', None, None, None, None),
    ]),
    ('Twisted Love 💕', 'twisted_love.jpg',[
        (1, 'You move back to town. Your brother’s best friend, Alex Volkov, is now your unexpected protector.', 'Welcome Alex', 'Keep your distance', 2, 3),
        (2, 'Alex keeps his distance, but something about him feels familiar… and cold.', 'Try to break his walls', 'Focus on your career', 4, 5),
        (3, 'You avoid Alex, but he always appears when you’re in danger—watching silently.', 'Confront him', 'Ignore him', 6, 7),
        (4, 'One night, Alex saves you from a mugger. You’re shaken, but grateful.', 'Open up emotionally', 'Brush it off', 8, 9),
        (5, 'Your photography career takes off, and you receive your first exhibition offer.', 'Celebrate with Alex', 'Go solo', 10, 11),
        (6, 'Alex finally confesses he’s been protecting you for years.', 'Ask him why', 'Tell him to stop', 12, 13),
        (7, 'You go on a date with someone else… but Alex shows up unexpectedly.', 'Talk to him', 'Ignore him again', 14, 15),
        (8, 'He opens up about his tragic past—his silence now makes sense.', 'Comfort him', 'Stay silent', 16, 17),
        (9, 'He withdraws, thinking you’re not interested in knowing him.', 'Explain your reaction', 'Let him go', 18, 19),
        (10, 'He shows up at your gallery with flowers in hand and a soft smile.', 'Kiss him', 'Thank him politely', 20, 21),
        (11, 'You spot Alex quietly admiring your photo, eyes filled with longing.', 'Approach him', 'Leave quietly', 22, 23),
        (12, 'He finally admits the truth: he’s in love with you.', 'Say it back', 'Stay silent', 24, 25),
        (13, 'He agrees to back off… but his eyes say everything.', 'Run after him', 'Stay strong', 26, 27),
        (14, 'He asks for one last chance—just one.', 'Give it', 'Refuse', 28, 29),
        (15, 'You realize you miss him more than you expected.', 'Message him', 'Move on', 30, 31),
        (16, 'Under the stars, he kisses you softly.', 'Kiss back', 'Pull away', 32, 33),
        (17, 'He leaves quietly without a word.', 'Call him', 'Let it be', 34, 35),
        (18, 'He looks back one last time before walking away.', 'Run to him', 'Close the door', 36, 37),
        (19, 'You dive into your dreams… but something always feels missing.', 'Try again', 'Fill the void with work', 38, 39),
        (20, 'He whispers, "I always knew it was you."', 'Say the same', 'Cry silently', 40, 41),
        (21, 'He walks away... but then turns around.', 'Run to him', 'Wave goodbye', 42, 43),
        (22, 'He smiles faintly and whispers, "Still beautiful."', 'Smile back', 'Look away', 44, 45),
        (23, 'You leave the gallery, but your heart feels heavy.', 'Call him later', 'Let go forever', 46, 47),
        (24, 'He pulls you into a tight hug, finally at peace.', None, None, None, None),
        (25, 'He nods slowly. "I understand." You part ways, hearts still full.', None, None, None, None),
        (26, 'You run after him in the rain and kiss him breathless.', None, None, None, None),
        (27, 'You close the door and lean against it, tears falling.', None, None, None, None),
        (28, 'You start fresh, choosing love again—with him.', None, None, None, None),
        (29, 'You walk away, wondering what could’ve been.', None, None, None, None),
        (30, 'Your message says: "Come back." He does.', None, None, None, None),
        (31, 'You try to move on, but he stays in your memories.', None, None, None, None),
        (32, 'He smiles through the kiss, finally yours.', None, None, None, None),
        (33, 'He respects your boundaries and walks away.', None, None, None, None),
        (34, 'You call. He picks up instantly. "I was hoping you would."', None, None, None, None),
        (35, 'You let go of the past and find peace in your solitude.', None, None, None, None),
        (36, 'You run to him , hug and whisper, "Don’t go."', None, None, None, None),
        (37, 'The door closes. Some stories aren’t meant to be.', None, None, None, None),
        (38, 'You try again, and this time—he stays.', None, None, None, None),
        (39, 'You bury yourself in work, but late at night, you still think of him.', None, None, None, None),
        (40, 'He smiles, pulling you into a kiss under the city lights.', None, None, None, None),
        (41, 'He wipes your tears. "You don’t have to say anything."', None, None, None, None),
        (42, 'You meet him halfway. No more running.', None, None, None, None),
        (43, 'He smiles softly and disappears into the crowd.', None, None, None, None), 
        (44, 'You both laugh, finally breaking the tension. He kisses you.', None, None, None, None),
        (45, 'You leave him standing there, a silent goodbye.', None, None, None, None),
        (46, 'Your voice trembles, but you call anyway. He answers.', None, None, None, None),
        (47, 'You leave the past behind… for good.', None, None, None, None)
    ]),
    ('Twisted Games 🖤', 'twisted_games.jpg',[
        (1, 'You’re Princess Bridget—dutiful, elegant, and secretly craving freedom. When your old bodyguard retires, a new one takes over: Rhys Larsen. Cold. Intense. Unshakeable.', 'Challenge his authority', 'Stay distant', 2, 3),
        (2, 'Rhys warns you to follow protocol. You smirk: *Or what? You’ll throw me in royal jail?*', 'Keep teasing him', 'Apologize (barely)', 4, 5),
        (3, 'He barely speaks to you—except when giving orders. But his eyes… always watchful.', 'Break the silence', 'Ignore him', 6, 7),
        (4, 'He grabs your wrist in a hallway. *You’re reckless,* he says. You reply, *You like that.*', 'Lean in', 'Pull away', 8, 9),
        (5, 'Rhys nods and walks off—but that look in his eyes? Not just professional.', 'Follow him', 'Let it go', 10, 11),
        (6, 'You ask him why he’s always so serious. He says, *Because I can\'t afford to slip.*', 'Ask why', 'Stay quiet', 12, 13),
        (7, 'You ignore him, but at night, you wonder what he’s thinking when he looks at you.', 'Sneak into his office', 'Text him', 14, 15),
        (8, 'Your faces are inches apart. Rhys says, *This can\'t happen.*', 'Kiss him', 'Back off', 16, 17),
        (9, 'You pull away. He steps back, jaw clenched. *Good,* he mutters, lying to both of you.', 'Stay away', 'Apologize', 18, 19),
        (10, 'You follow him outside. *Why do you care so much?* He turns slowly: *Because I feel everything.*', 'Admit your feelings', 'Play it cool', 20, 21),
        (11, 'You let it go, but his presence lingers in your mind, a storm you can’t escape.', 'Confess to a friend', 'Hide it', 22, 23),
        (12, '*Because I’ve already slipped once,* Rhys says. *With you.*',  'Ask when',  'Stay silent', 24, 25),
        (13, 'He looks disappointed at your silence. You’ve built a wall, but you hate the cold.', 'Break the wall', 'Keep it up', 26, 27),
        (14, 'You find a letter he never sent: *Protecting you isn’t the problem. Loving you is.*',  'Confront him', 'Read more', 28, 29),
        (15, '*Stop texting me,* Rhys replies. *You’re not safe when we talk like this.*', 'Call him', 'Block him', 30, 31),
        (16, 'He kisses you like it’s the end of the world—because for both of you, it might be.', 'Stay with him', 'Push him away', 32, 33),
        (17, 'You break away. Rhys nods and leaves. That kiss never happened. Except it did—in your heart.', 'Move on',  'Chase him',  34, 35),
        (18, 'You avoid him, but every royal event feels colder without his gaze.', 'Talk to him', 'Stay guarded', 36, 37),
        (19, 'You whisper, *I’m sorry.* Rhys pauses, his armor cracking.', 'Hug him', 'Say nothing', 38, 39),
        (20, 'Rhys says, *Then damn the rules.* And kisses you under the palace moonlight.', None, None, None, None),
        (21, 'He turns away. You’ll always wonder what could’ve been.', None, None, None, None),
        (22, 'Your friend warns you: *He’s danger. But maybe danger’s what you need.*', None, None, None, None),
        (23, 'No one knows your secret. Except your heart—and that traitorous ache.', None, None, None, None),
        (24, 'He tells you about the night you almost kissed. *Since then, I’ve been ruined.*', None, None, None, None),
        (25, 'You leave him in silence. A story left unfinished.', None, None, None, None),
        (26, 'You finally let him in. And find love, fierce and fearless.', None, None, None, None),
        (27, 'You keep the crown, but lose the man who would’ve risked everything.', None, None, None, None),
        (28, 'You burst into his room. He says, *I wrote that after I saw you cry.*', None, None, None, None),
        (29, 'You read every letter. And realize he’s loved you all along.', None, None, None, None),
        (30, 'He answers the call with a hoarse whisper: *I can’t stop thinking about you.*', None, None, None, None),
        (31, 'You block him—but your soul still whispers his name.', None, None, None, None),
        (32, 'You choose love, and face the consequences—together.', None, None, None, None),
        (33, 'You break the kiss. His pain matches yours. But rules win.', None, None, None, None),
        (34, 'You try to move on… but no one compares.', None, None, None, None),
        (35, 'You chase him—he’s still waiting, heart in hand.', None, None, None, None),
        (36, 'You talk, and he tells you, *I never stopped.*', None, None, None, None),
        (37, 'You keep the walls up, alone on your throne.', None, None, None, None),
        (38, 'He hugs you back—tightly, desperately. *Don’t shut me out again,* he whispers.', None, None, None, None),
        (39, 'He walks away. You feel the loss in your bones.', None, None, None, None)
    ]),
    ('Twisted Hate 🔥', 'twisted_hate.jpg',[
        (1, 'You’re forced to work with your sworn enemy, Josh Chen, on a legal aid project. He’s smug, arrogant, and infuriatingly hot.', 'Argue with him', 'Keep it professional', 2, 3),
        (2, 'Your constant bickering becomes the talk of the office. But one night, an argument turns into something... different.', 'Lean into the tension', 'Avoid him', 4, 5),
        (3, 'You keep things polite—but he starts teasing you anyway, with that crooked smirk.', 'Call him out', 'Ignore him', 6, 7),
        (4, 'You share a heated kiss after hours. Neither of you mention it… but everything changes.', 'Act normal', 'Avoid eye contact', 8, 9),
        (5, 'You stay away, but the tension grows. He texts you: *Still pretending you don’t feel it?*', 'Reply sarcastically', 'Don’t respond', 10, 11),
        (6, 'He admits he enjoys riling you up. *You’re cute when you’re mad,* he says.', 'Snap back', 'Blush', 12, 13),
        (7, 'He starts getting under your skin—so much that you start dreaming about him.', "Confront him", "Confide in a friend", 14, 15),
        (8, 'You both pretend nothing happened… until you’re stuck working late again.', 'Bring it up', 'Let it go', 16, 17),
        (9, 'He notices your awkwardness. *We need to talk,* he says softly.', 'Agree', 'Walk away', 18, 19),
        (10, '*Careful, Chen,* you text. *You might fall for me.*', 'Send it', 'Delete it', 20, 21),
        (11, 'You leave him on read. He shows up at your door that night.', 'Let him in', 'Shut the door', 22, 23),
        (12, '*You are impossible,* you snap. He only grins wider.', 'Storm off', 'Stay and talk', 24, 25),
        (13, 'He catches your blush and softens. *Maybe you’re not as icy as you act.*', 'Admit you like him', 'Stay silent', 26, 27),
        (14, 'You tell your best friend, who warns: *Don’t fall for a man like that.*', 'Ignore her',  'Take her advice', 28, 29),
        (15, 'Your friend offers to set you up with someone else. Josh finds out… and hates it.', 'Talk to Josh',  'Go on the date', 30, 31),
        (16, 'You ask, *What was that kiss?* He replies, *Everything.*', 'Kiss again', 'Back away', 32, 33),
        (17, 'The silence is unbearable. You miss him more than you thought possible.', 'Call him', 'Move on',  34, 35),
        (18, 'You meet at a rooftop. The city lights fade as he says, *I never hated you.*', 'Confess your feelings', 'Stay guarded', 36, 37),
        (19, 'He watches you leave, eyes full of regret.', 'Turn around', 'Keep walking', 38, 39),
        (20, 'He replies: *Too late. Already did.*', None, None, None, None),
        (21, 'You never send the text, but wish you had.', None, None, None, None),
        (22, 'He says, *I couldn’t stop thinking about you.*', None, None, None, None),
        (23, 'He leaves without a word. That was your last chance.', None, None, None, None),
        (24, 'He grabs your wrist. *Stay.*', None, None, None, None),
        (25, 'You talk all night, no more pretending.', None, None, None, None),
        (26, 'He pulls you in and says, *I like you too.*', None, None, None, None),
        (27, 'He gives a sad smile and walks away.', None, None, None, None),
        (28, 'You choose him. Love wins, despite the past.', None, None, None, None),
        (29, 'You walk away before it ever began.', None, None, None, None),
        (30, 'You talk. He admits he’s jealous… and maybe in love.', None, None, None, None),
        (31, 'The date’s fine—but your heart is already taken.', None, None, None, None),
        (32, 'This time, the kiss isn’t a mistake—it’s a promise.', None, None, None, None),
        (33, 'You pull away, too scared to fall.', None, None, None, None),
        (34, 'varsYou call. He says, *I was waiting for you.*', None, None, None, None),
        (35, 'You focus on healing—but part of you stays with him.', None, None, None, None),
        (36, 'You fall for him—hard. This time, it is real.', None, None, None, None),
        (37, 'You stay guarded, and the moment passes forever.', None, None, None, None),
        (38, 'You turn back. He’s still there, waiting.', None, None, None, None),
        (39, 'You never see him again—but you never forget.', None, None, None, None)
    ]),
    ('Twisted Lies 🕸️', 'twisted_lies.jpg', [
        (1, 'You’re Stella. Fashion influencer by day, hopeless romantic by heart. Your hot neighbor Christian Harper offers to be your fake boyfriend—to help with a stalker, he says.', 'Agree to the plan', 'Refuse politely', 2, 3),
        (2, 'Christian gives you a smile that could melt steel. Don’t worry, sweetheart. I don’t bite—unless asked.', 'Blush and play along', 'Tell him to behave', 4, 5),
        (3, 'You say no. He shrugs. But you feel his eyes linger as you walk away.', 'Text him later', 'Ignore the heat', 6, 7),
        (4, 'Fake dates start. Christian plays his role a little too well. You almost forget it’s fake.', 'Ask him why he’s doing this', 'Enjoy the moment', 8, 9),
        (5, 'Strict boundaries,you say. Christian’s smirk fades a little, but his eyes still linger.', 'Stick to business', 'Let loose', 10, 11),
        (6, 'You text him: Still offering that fake boyfriend deal? He replies: For you? Always.', 'Say yes', 'Say you’re joking', 12, 13),
        (7, 'You ignore him, but when the stalker calls again—you wish he was by your side.', 'Call Christian', 'Handle it alone', 14, 15),
        (8, 'He answers your question with a grin: Maybe I just like seeing you smile.', 'Smile back', 'Roll your eyes', 16, 17),
        (9, 'His hand finds yours during dinner. Your pulse jumps. This isn’t just pretend anymore.', 'Pull away', 'Squeeze back', 18, 19),
        (10, 'Christian keeps his distance—but always close enough to catch you if you fall.', 'Test the distance', 'Keep it professional', 20, 21),
        (11, 'You loosen up and laugh more. But Christian’s touches linger longer than they should.', 'Ask him directly', 'Ignore it', 22, 23),
        (12, 'You agree. His reply: Then let’s give them a show they’ll never forget.', 'Flirt back', 'Play it cool', 24, 25),
        (13, 'That’s a shame, he texts. I would’ve treated you like you deserved.', 'Change your mind', 'Leave it there', 26, 27),
        (14, 'He shows up within minutes. No one touches what’s mine, he says.', 'Tell him it’s not real', 'Stay quiet', 28, 29),
        (15, 'You handle the call—but you cry afterward. Alone.', 'Reach out to Christian', 'Keep it inside', 30, 31),
        (16, 'You smile. His eyes darken. Careful, he says. I might take that as permission.', 'Tease him', 'Look away', 32, 33),
        (17, 'You roll your eyes. But the blush on your cheeks betrays you.', 'Admit your feelings', 'Keep playing it cool', 34, 35),
        (18, 'You pull away—but your heart stays tangled.', None, None, None, None),
        (19, 'You squeeze back. The lie turns into something real.', None, None, None, None),
        (20, 'You step closer one night—and he doesn’t stop you.', None, None, None, None),
        (21, 'You keep your walls up. So does he. And nothing ever crosses.', None, None, None, None),
        (22, 'You ask, and he replies, Because I can’t pretend anymore.', None, None, None, None),
        (23, 'You ignore it—but his silence becomes louder than any words.', None, None, None, None),
        (24, 'You’re dangerous, you say. You have no idea, he replies before pulling you in.', None, None, None, None),
        (25, 'You stay cool. But your eyes say everything your mouth won’t.', None, None, None, None),
        (26, 'You text again: I changed my mind. He’s at your door five minutes later.', None, None, None, None),
        (27, 'You leave it there. And live with the what-if.', None, None, None, None),
        (28, 'Tell me it’s real, he says. You hesitate.', None, None, None, None),
        (29, 'You stay quiet—and his arms become your home.', None, None, None, None),
        (30, 'He finds you crying. Doesn’t speak—just holds you like he means it.', None, None, None, None),
        (31, 'You keep it inside. But your soul knows who you needed.', None, None, None, None),
        (32, 'You tease him. He pins you with that look. Say the word.', None, None, None, None),
        (33, 'You look away. He lets you go. But not from his heart.', None, None, None, None),
        (34, 'You finally admit it. And he’s all in—no more pretending.', None, None, None, None),
        (35, 'You keep pretending. And wonder if he ever truly felt the same.', None, None, None, None)
    ]),

]

for title, image, steps in stories:
    c.execute('INSERT INTO stories (title, image) VALUES (?, ?)', (title, image))
    sid = c.lastrowid
    for step in steps:
        step_number, content, opt1, opt2, nxt1, nxt2 = step
        c.execute('''
            INSERT INTO steps (story_id, step_number, content, option1, option2, next1, next2)
            VALUES (?, ?, ?, ?, ?, ?, ?)
        ''', (sid, step_number, content, opt1, opt2, nxt1, nxt2))

conn.commit()
conn.close()
print('stories.db created with existing and new romantic stories and images.')